server:
  port: 8866
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/blog_backend_db

  jpa:
    hibernate:
      ddl-auto: create # prod use update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        hbm2ddl:
          auto: update